### ISSUE TITLE
pls add support commex.com

### ISSUE THREAD

**Issue by master88wi** [thrasher-corp/gocryptotrader#1367]
pls add support commex.com
commex api = api binance
https://www.commex.com/api-docs/en/index.html#commex-rest-open-api

**Comment by shazbert** [comment]
It's unlikely that we'll be able to prioritize implementing this exchange due to its limited adoption and low liquidity. Our focus is on providing native support for the [top 20 exchanges](https://www.coingecko.com/en/exchanges), which allows us to serve a broader user base effectively.

For your specific needs, we recommend considering a bespoke implementation tailored to the unique characteristics of this exchange. If you require assistance or guidance in developing this custom integration, please feel free to reach out.

**Comment by master88wi** [comment]
Commex API = API Binance

**Comment by shazbert** [comment]
> Commex API = API Binance

I disagree, it is similar on some endpoints but it's not 1:1 mapping. This requires work, a full review process and complete ongoing maintenance. 

As above stands; very happy for you to copy and paste the Binance implementation into your own bespoke implementation and if liquidity levels improve open a PR at your convenience. Please feel free to reach out if you need guidance.

**Comment by thrasher-** [comment]
Closed as this exchange no longer exists
