### ISSUE TITLE
When will the official version be released?

### ISSUE THREAD

**Issue by zhihuba** [thrasher-corp/gocryptotrader#913]
- When will the official version be released
- When to provide Documentation
- Looking at the code structure, it seems to be each independent module, but I can't call it separately, only through GRPC

**Comment by zoh** [comment]
+ Documentation

How use that staf?

**Comment by thrasher-** [comment]
Since things are always in a moving state and considering there's money at risk, we've opted to not have an official semver yet to explicitly warn people about the potential risk of not being production ready. In saying that, we use various components of GCT internally with success but that's because we're familiar with it.

Documentation can be found here: https://github.com/thrasher-corp/gocryptotrader/tree/master/docs or in the various features doc links: https://github.com/thrasher-corp/gocryptotrader?tab=readme-ov-file#current-features

You can use GCT in four major ways:
1) Lib usage via individual exchange packages
2) Engine/gRPC functionality which the default main POC uses and is managed with gctcli https://github.com/thrasher-corp/gocryptotrader/tree/master/cmd/gctcli
3) gctscript https://github.com/thrasher-corp/gocryptotrader/tree/master/gctscript#how-to-use
4) Backtester https://github.com/thrasher-corp/gocryptotrader/blob/master/backtester/README.md

Closing this as it's dated and technically not an issue.
